version: '3'

volumes:
  db_data:

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 33006:3306
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  reports:
    image: metabase/metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: '3306'
      MB_DB_USER: root
      MB_DB_PASS: root
      MB_DB_HOST: db
    
  backend:
    build: . 
    image: php:8-apache
    volumes:
      - ./src:/var/www/html:z
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=formulario

  nginx:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:  
      - 8000:80
    depends_on:
      - backend